### 🔐 Crear Usuario
POST localhost:8091/user/signup
Content-Type: application/json

{
  "name": "ricardo",
  "contactNumber": "949493742",
  "email": "ricardo@gmail.com",
  "password": "123456"
}



### 🔑 Iniciar Sesión
POST localhost:8091/user/login
Content-Type: application/json

{"email": "edwin@gmail.com", "password":"123456"}



### 🔑 Get User iniciando con el token
GET localhost:8091/user/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJlZHdpbkBnbWFpbC5jb20iLCJpYXQiOjE3NDkwNzQyMDgsImV4cCI6MTc0OTExMDIwOH0.vUmJAKrQE8u7jbZfSAbYtqPg0BJ7NvNlwpf1K9oXX2Q